16:29:42:673|SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:29:42:682|SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:29:42:714|SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:29:42:720|SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:29:42:741|FAILURE   |               |tbl_query      |database_*le_util.py|unable to execute query [select col1,col2,col3 from foofoo] in db [.//foobar.sqlite] [no such table: foofoo]
16:29:42:767|SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:29:42:774|SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:29:42:805|SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:29:42:818|SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:29:42:837|INFO      |               |_parse*ut_file |excel_dat*se_util.py|setting runtime_path to [.]
